defaults:
- robotwin_adjust_bottle_rlt_fastwam_single_gpu
- _self_
runner:
  max_steps: 800
  max_epochs: 2000
  logger:
    log_path: /data/chenyiteng/results/rlinf-rlt/fastwam-rlt-clean-half4env-fresh800-phys4-20260919-v1
    experiment_name: fastwam-rlt-clean-half4env-fresh800-phys4-20260919-v1
cluster:
  component_placement:
    actor,env,rollout: 4
actor:
  global_batch_size: 512
  micro_batch_size: 256
env:
  train:
    total_num_envs: 4
    seeds_path: /data/chenyiteng/projects/rlinf-shenzhen/worktrees/fastwam-rlt-clean4-800-20260919/tools/fastwam_clean4_inputs/train_seeds.json
    task_config:
      save_path: /data/chenyiteng/results/rlinf-rlt/fastwam-rlt-clean-half4env-fresh800-phys4-20260919-v1/robotwin_data/train
    video_cfg:
      video_base_dir: /data/chenyiteng/results/rlinf-rlt/fastwam-rlt-clean-half4env-fresh800-phys4-20260919-v1/video/train
  eval:
    seeds_path: /data/chenyiteng/projects/rlinf-shenzhen/worktrees/fastwam-rlt-clean4-800-20260919/tools/fastwam_clean4_inputs/eval_seeds.json
    task_config:
      save_path: /data/chenyiteng/results/rlinf-rlt/fastwam-rlt-clean-half4env-fresh800-phys4-20260919-v1/robotwin_data/eval
    video_cfg:
      video_base_dir: /data/chenyiteng/results/rlinf-rlt/fastwam-rlt-clean-half4env-fresh800-phys4-20260919-v1/video/eval
    total_num_envs: 4
algorithm:
  rlt_schedule:
    enable: true
    max_updates_per_train_step: 800
    warmup_min_size: 10000
    warmup_post_collect_updates: 15000
    train_every_episodes: 0
    train_every_transitions: 1
  actor_weight_schedule:
    enable: true
    warmup_updates: 10000
    ramp_updates: 25000
    warmup_bc_weight: 7.0
    warmup_q_weight: 0.05
    online_bc_weight: 2.5
    online_q_weight: 0.45
  replay_buffer:
    enable_cache: true
    cache_size: 80000
    sample_window_size: 80000
    min_buffer_size: 1
    auto_save: false
  update_epoch: 5
  critic_actor_ratio: 2
  gamma: 0.99
  tau: 0.005
  reference_dropout_prob: 0.5
  rlt_dvac:
    mode: 'off'
