defaults:
  - _self_
  - agent: baku
  - suite: libero
  - dataloader: libero
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: 

# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true
batch_size: 64

#### experiment flag
use_save_demo: true ###
save_demo_path: [
  ]
num_demo_per_round: []
use_ema: false

# experiment
obs_type: "pixels" # pixels, features
num_demos_per_task: 8 # for fewshot
encoder_type: 'resnet' # base, resnet
policy_type: 'gpt' # mlp, gpt
policy_head: deterministic # deterministic, gmm, bet, diffusion, vqbet
use_proprio: true
use_language: true
use_actions: false
prompt: text # text, goal, intermediate_goal
eval: false
benchmarking: false
experiment: train
experiment_label: none

# action chunking
temporal_agg: true # aggregate actions over time
num_queries: 10

# expert dataset
expert_dataset: ${dataloader.bc_dataset}

# Load weights
load_bc: true
bc_weight: 

hydra:
  run:
    dir: 
  sweep:
    dir: 
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder:
