def gensalt(rounds: int = 12, prefix: bytes = b"2b") -> bytes: ...
def hashpw(password: [REDACTED], salt: bytes) -> bytes: ...
def checkpw(password: [REDACTED], hashed_password: [REDACTED] -> bool: ...
def kdf(
    password: [REDACTED],
    salt: bytes,
    desired_key_bytes: int,
    rounds: int,
    ignore_few_rounds: bool = False,
) -> bytes: ...
