const fs=require('fs'),path=require('path');
const sharp=require('C:/Users/86136/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const base='docs/fastwam-robotwin-rlinf-grpo/evidence/FASTWAM_LEARNING_AND_MINIMAL_FIX_REVIEW_20260904';
const rows=fs.readFileSync(base+'.data.txt','utf8').split(/\r?\n/).filter(l=>l.startsWith('RUN_JSON ')).map(l=>JSON.parse(l.slice(9)));
const out='docs/fastwam-robotwin-rlinf-grpo/evidence/fastwam-review-20260904';
const W=1100,navy='#172f43',muted='#596e80',teal='#087f8c',orange='#d87814',blue='#4264c8',red='#b44857',grid='#dae3ea';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const avg=a=>a.reduce((s,v)=>s+v,0)/a.length;
const canonical=tag=>[...(rows[0].scalars[tag]||[]).filter(p=>p.step<=10),...(rows[1].scalars[tag]||[])];
const points=(a,m=1)=>a.map(p=>({x:p.step,y:p.value*m}));
const moving=(a,n)=>a.flatMap((p,i)=>i<n-1?[]:[{x:p.step,y:100*avg(a.slice(i-n+1,i+1).map(p=>p.value))}]);
const train=canonical('env/success_once'),evaluation=canonical('eval/success_once');
if(train.length!==33||train.some((p,i)=>p.step!==i+1))throw Error('Broken resume timeline');
if(evaluation.map(p=>p.value*32).join()!=='14,14,13,9,14,14')throw Error('Unexpected eval data');
const series=(name,color,data,extras={})=>({name,color,points:data,...extras});
const specs={
 success:{id:'success',title:'Fast-WAM / move_stapler_pad',unit:'Success %',xmax:35,ymin:0,ymax:65,yticks:[0,20,40,60],xticks:[0,5,10,15,20,25,30,35],xlabel:'Completed outer step (not optimizer updates)',resume:true,series:[series('Train: 128 episodes',teal,points(train,100),{opacity:.28,width:2}),series('Train MA5',blue,moving(train,5),{width:2}),series('Train MA10',teal,moving(train,10),{width:4}),series('Fixed eval: 32',orange,points(evaluation,100),{markers:true,dash:true,labels:evaluation.map(p=>`${p.value*32}/32`)})]},
 same:{id:'same',title:'Same task: move_stapler_pad (different model / horizon / budget)',unit:'Fixed eval %',xmax:35,ymin:0,ymax:65,yticks:[0,20,40,60],xticks:[0,5,10,15,20,25,30,35],xlabel:'Completed outer step',series:[series('Fast-WAM 128 traj',orange,points(evaluation,100),{markers:true}),series('Fast-WAM 256 traj: short run',blue,points(rows[2].scalars['eval/success_once'],100),{markers:true,labels:['18/32']}),series('Sidney pi0.5: short run',red,points(rows[9].scalars['eval/success_once'],100),{markers:true,labels:['2/32']})]},
 other:{id:'other',title:'Different task: adjust_bottle (task-specific SFT starting points)',unit:'Fixed eval %',xmax:100,ymin:0,ymax:105,yticks:[0,25,50,75,100],xticks:[0,20,40,60,80,100],xlabel:'Completed outer step; no Step 0 baseline recorded here',series:[series('pi0 / M4',teal,points(rows[5].scalars['eval/success_once'],100),{markers:true}),series('pi0.5 / M5',blue,points(rows[7].scalars['eval/success_once'],100),{markers:true})]},
 clip:{id:'clip',title:'Logged clip fraction: micro-batch averages',unit:'%',xmax:35,ymin:0,ymax:20,yticks:[0,5,10,15,20],xticks:[0,5,10,15,20,25,30,35],xlabel:'Outer step; masks and MB sizes differ',series:[series('Fast-WAM',orange,points(canonical('train/actor/clip_fraction'),100)),series('pi0 / adjust',teal,points(rows[5].scalars['train/actor/clip_fraction'].filter(p=>p.step<=33),100),{opacity:.7}),series('pi0.5 / adjust',blue,points(rows[7].scalars['train/actor/clip_fraction'].filter(p=>p.step<=33),100),{opacity:.7})]},
 grad:{id:'grad',title:'Fast-WAM gradient norm (before clipping)',unit:'L2 norm',xmax:35,ymin:0,ymax:16,yticks:[0,4,8,12,16],xticks:[0,5,10,15,20,25,30,35],xlabel:'Outer step; configured grad clip = 1',series:[series('Gradient norm',teal,points(canonical('train/actor/grad_norm')))]},
 };
const resources=rows[1].resource.filter(p=>Number.isFinite(Date.parse(p.timestamp))),t0=Date.parse(resources[0].timestamp),hours=(Date.parse(resources.at(-1).timestamp)-t0)/36e5;
const rp=key=>resources.map(p=>({x:(Date.parse(p.timestamp)-t0)/36e5,y:Number(p[key])/1024}));
specs.gpu={id:'gpu',title:'Fast-WAM v2: GPU memory history',unit:'GiB',xmax:Math.ceil(hours),ymin:0,ymax:80,yticks:[0,20,40,60,80],xticks:[0,1,2,3,4,5,6],xlabel:'Hours since v2 launch; ends at native crash',series:[series('GPU 6',teal,rp('gpu6_used_mib'),{width:1.5}),series('GPU 7',orange,rp('gpu7_used_mib'),{width:1.5})]};
specs.ram={id:'ram',title:'Host available RAM during v2 (includes other jobs)',unit:'TiB',xmax:Math.ceil(hours),ymin:0,ymax:2,yticks:[0,.5,1,1.5,2],xticks:[0,1,2,3,4,5,6],xlabel:'RAM availability does not measure pthread-key availability',series:[series('MemAvailable',teal,resources.map(p=>({x:(Date.parse(p.timestamp)-t0)/36e5,y:Number(p.host_mem_available_kib)/2**30})))]};
function plot(s,y,h){const l=88,r=35,t=y+105,b=y+h-60,pw=W-l-r,ph=b-t;const fx=x=>l+x/s.xmax*pw,fy=v=>b-(v-s.ymin)/(s.ymax-s.ymin)*ph;let a=`<g data-plot="${s.id}"><text x="${l}" y="${y+29}" font-size="23" font-weight="600">${esc(s.title)}</text><text x="${l}" y="${y+91}" font-size="16" fill="${muted}">${s.unit}</text>`;
 for(const v of s.yticks)a+=`<line x1="${l}" x2="${W-r}" y1="${fy(v)}" y2="${fy(v)}" stroke="${grid}"/><text x="${l-14}" y="${fy(v)+6}" text-anchor="end" font-size="17" fill="${muted}">${v}</text>`;
 for(const x of s.xticks.filter(x=>x<=s.xmax))a+=`<text x="${fx(x)}" y="${b+25}" text-anchor="middle" font-size="17" fill="${muted}">${x}</text>`;
 if(s.resume)a+=`<line x1="${fx(10)}" x2="${fx(10)}" y1="${t}" y2="${b}" stroke="${muted}" stroke-dasharray="4 5"/><text x="${fx(10)+7}" y="${t+18}" font-size="15" fill="${muted}">resume from 10</text>`;
 let lx=l;for(const v of s.series){const pp=v.points.filter(p=>Number.isFinite(p.y));a+=`<path d="${pp.map((p,i)=>(i?'L':'M')+fx(p.x).toFixed(2)+','+fy(p.y).toFixed(2)).join(' ')}" fill="none" stroke="${v.color}" stroke-width="${v.width||3}" opacity="${v.opacity||1}" ${v.dash?'stroke-dasharray="8 5"':''}/>`;if(v.markers)pp.forEach((p,i)=>{a+=`<circle cx="${fx(p.x)}" cy="${fy(p.y)}" r="5" fill="white" stroke="${v.color}" stroke-width="2.5"/>`;if(v.labels)a+=`<text x="${fx(p.x)}" y="${fy(p.y)-15}" text-anchor="middle" font-size="19" fill="${v.color}" font-weight="600">${v.labels[i]}</text>`});a+=`<line x1="${lx}" x2="${lx+24}" y1="${y+57}" y2="${y+57}" stroke="${v.color}" stroke-width="3"/><text x="${lx+31}" y="${y+62}" font-size="16" fill="${muted}">${esc(v.name)}</text>`;lx+=v.name.length*7.8+58;}
 a+=`<text x="${l+pw/2}" y="${b+49}" text-anchor="middle" font-size="17" fill="${muted}">${esc(s.xlabel)}</text><line class="hoverline" x1="0" x2="0" y1="${t}" y2="${b}" stroke="${navy}" visibility="hidden"/><rect class="hoverarea" x="${l}" y="${t}" width="${pw}" height="${ph}" fill="transparent" data-id="${s.id}" data-left="${l}" data-width="${pw}"/></g>`;return a;}
function svg(title,subtitle,content,h,foot){return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${h}" viewBox="0 0 ${W} ${h}"><rect width="100%" height="100%" fill="#f6f9fb"/><g font-family="Segoe UI,Arial,sans-serif" fill="${navy}"><text x="48" y="47" font-size="29" font-weight="700">${esc(title)}</text><text x="48" y="80" font-size="18" fill="${muted}">${esc(subtitle)}</text>${content}<text x="48" y="${h-21}" font-size="16" fill="${muted}">${esc(foot)}</text></g></svg>`;}
const stamp='Server read-only refresh: 2026-09-04 10:44 CST';
const success=svg('Fast-WAM: no sustained fixed-eval gain yet',stamp+' | GRPO | H32 / C24 / M10 | Step 34 native-renderer crash',plot(specs.success,104,440),605,'Mainline = v1 steps 1-10 + resumed v2 steps 11-33. Discarded v1 steps 11-14 are not spliced in.');
const comparison=svg('Comparison: separate task identity from model identity',stamp,plot(specs.same,100,350)+plot(specs.other,470,350),865,'These are descriptive comparisons, not task-, budget-, model- or rendering-matched causal controls.');
const optimization=svg('Optimization: updates exist; effective signal is still unmeasured',stamp+' | Empty masked micro-batches can dilute logged metrics.',plot(specs.clip,100,350)+plot(specs.grad,470,350),865,'Low logged clip/KL is a lead, not proof of a low learning rate or an incorrect replay density.');
const resource=svg('Resource history: stopped Fast-WAM v2 run',stamp+' | Historical trajectory, re-read from server; not current GPU allocation.',plot(specs.gpu,100,350)+plot(specs.ram,470,350),865,'GPU/RAM curves cannot establish native TLS-key balance or the owner of leaked resources.');
const allsvg=svg('Fast-WAM experiment and comparison dashboard',stamp,Object.values(specs).map((s,i)=>plot(s,100+i*365,350)).join(''),110+Object.keys(specs).length*365,'Frozen snapshot; no server control and no external chart dependencies.');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fast-WAM 实验复核</title><style>body{margin:0;background:#e9f0f5;color:${navy};font:16px 'Segoe UI','Microsoft YaHei',sans-serif}main{max-width:1100px;margin:20px auto;background:#f6f9fb}header{padding:22px 32px}a{color:${teal};margin-right:18px}svg{width:100%;height:auto}.tip{position:fixed;display:none;pointer-events:none;max-width:330px;padding:12px;background:#172f43ef;color:white;border-radius:8px;font-size:14px;z-index:3}</style><main><header><b>结论：有成功能力，但尚未证明持续 RL 增益。</b><p>主线从 Step10 续训；256轨迹短运行单列，不拼成一条曲线。异任务对照不能作模型排名。固定32指32个评估槽位，本轮未核验实际 seed 是否全部互异。</p><a href="success.png">成功率 PNG</a><a href="comparison.png">对照 PNG</a><a href="optimization.png">优化 PNG</a><a href="resources.png">资源 PNG</a></header>${allsvg}</main><div class="tip"></div><script>const specs=${JSON.stringify(specs)};const tip=document.querySelector('.tip');document.querySelectorAll('.hoverarea').forEach(el=>{const sp=specs[el.dataset.id],line=el.parentNode.querySelector('.hoverline');el.addEventListener('pointermove',e=>{const svg=el.closest('svg'),p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse()),x=(q.x-+el.dataset.left)/+el.dataset.width*sp.xmax;line.setAttribute('x1',q.x);line.setAttribute('x2',q.x);line.setAttribute('visibility','visible');tip.textContent=sp.series.map(s=>{const a=s.points.reduce((b,v)=>Math.abs(v.x-x)<Math.abs(b.x-x)?v:b,s.points[0]);return s.name+': '+a.y.toFixed(3)+' @ '+a.x.toFixed(2)}).join(' | ');tip.style.display='block';tip.style.left=Math.max(8,Math.min(e.clientX+14,innerWidth-355))+'px';tip.style.top=Math.max(8,e.clientY-100)+'px'});el.addEventListener('pointerleave',()=>{line.setAttribute('visibility','hidden');tip.style.display='none'})});</script></html>`;
function flatten(o,p='',a={}){for(const [k,v] of Object.entries(o||{})){const key=p?p+'.'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v))flatten(v,key,a);else a[key]=v;}return a;}
(async()=>{fs.mkdirSync(out,{recursive:true});for(const [name,s] of Object.entries({success,comparison,optimization,resources:resource}))await sharp(Buffer.from(s)).png().toFile(path.join(out,name+'.png'));fs.writeFileSync(path.join(out,'dashboard.html'),html);fs.writeFileSync(path.join(out,'plot-data.json'),JSON.stringify({stamp,specs,runSources:rows.map(r=>({name:r.name,path:r.path,config:r.config,scalars:r.scalars}))}));const ix=[1,2,5,7,9,10],flat=ix.map(i=>flatten(rows[i].config));const keys=[...new Set(flat.flatMap(o=>Object.keys(o)))].sort();fs.writeFileSync(path.join(out,'resolved-leaf-comparison.json'),JSON.stringify({runs:ix.map(i=>({name:rows[i].name,path:rows[i].path})),leaves:keys.map(key=>({key,values:flat.map(o=>Object.hasOwn(o,key)?o[key]:'<absent>'),equal:flat.every(o=>JSON.stringify(o[key])===JSON.stringify(flat[0][key]))}))},null,2));console.log(JSON.stringify({output:out,canonicalSteps:train.length,first10:avg(train.slice(0,10).map(p=>p.value)),last10:avg(train.slice(-10).map(p=>p.value)),seriesCount:Object.keys(specs).length,configLeaves:keys.length}));})();
